name: alpinephp74

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - run: |
          VERSION=$(date +%s)
          docker login -u andersondmelo -p ${{ secrets.SECRET_KEY }}
          docker build . --file Dockerfile --tag andersondmelo/alpinephp74:${VERSION}
          docker push andersondmelo/alpinephp74:${VERSION}
